config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "home#index"

  resources :hooks
  resources :posts, only: [:index, :show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hook.rb
class Hook < Resource
	has_many :posts
	
	validates :url, presence: true, length: { minimum: 5 }
	#validates_format_of :url, with: /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/i

	def self.empty_fields
		{ url: nil }
	end

	def self.set(hook, params)
	  hook.url = params[:url]
	end
end

app/models/post.rb
class Post < Resource
	belongs_to :hook

	validates :message, presence: true
	
	def self.empty_fields
		{ message: nil }
	end

	def self.set(post, params)
	  post.message = params[:message]
	end
end

app/models/resource.rb
class Resource < ActiveResource::Base
	self.site = ENV["HOOTSUITE_WEBHOOKS_SERVER_API"]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/hooks_controller.rb
class HooksController < ApplicationController
  before_action :set_hook, only: [:show, :edit, :update, :destroy]

  def index
    @hooks = Hook.all
  end

  def show
    @post = Post.new(Post.empty_fields)
  end

  def new
    @hook = Hook.new(Hook.empty_fields)
  end

  def create
    @hook = Hook.new(hook_params.to_h)

    if @hook.save
      flash[:notice] = t('flash.hook.create')

      redirect_to hooks_path
    else
      flash[:error] = t('flash.hook.create_error')

      render :new
    end
  end

  def edit
  end

  def update
  	Hook.set(@hook, hook_params)

    if @hook.save
      flash[:notice] = t('flash.hook.update')

      redirect_to hooks_path
    else
      flash[:error] = t('flash.hook.update_error')

      render :edit
    end
  end

  def destroy
    if @hook.destroy
      flash[:notice] = t("flash.hook.destroy")
    else
      flash[:error] = t("flash.hook.destroy_error")
    end

    redirect_to hooks_path
  end

private

  def set_hook
    @hook = Hook.find(params[:id])
  end

  def hook_params
    params.require(:hook).permit(:url)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  def index
    redirect_to hooks_path if params[:hook_id].nil?

    @posts = Post.where(posts: { hook_id: params[:hook_id] })
    @hook = @posts[0].hook
  end

  def show
  end

  def new
    @post = Post.new(Post.empty_fields)
  end

  def create
    @post = Post.new(post_params.to_h)

    if @post.save
      flash[:notice] = t('flash.post.create')
    else
      flash[:error] = t('flash.post.create_error')
    end

    redirect_to posts_path(hook_id: @post.hook.id)
  end

=begin
  def destroy
    if @post.destroy
      flash[:notice] = t("flash.post.destroy")
    else
      flash[:error] = t("flash.post.destroy_error")
    end

    redirect_to posts_path(hook_id: @post.hook.id)
  end
=end

private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:message, :hook_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hooks_helper.rb
module HooksHelper
end

app/views/hooks/_form.html.erb
<%= form_for(@hook, url: url, class: "form-horizontal") do |f| %>
  <div class="box-body">
    <div class="form-group">
      <%= f.label :url, class: "col-sm-2 control-label" %>

      <div class="col-sm-10">
        <%= f.text_field :url, class: "form-control", placeholder: "URL" %>
      </div>

      <br />
    </div>

    <div class="box-footer">
      <%= f.submit class: "btn btn-primary" %>

      <%= link_to hooks_path, class: "btn btn-default" do %><i class="fa fa-undo"></i><%= t('actions.back') %><% end %>
    </div>
  </div>
<% end %>

app/views/hooks/edit.html.erb
<section class="content">  
  <div class="row">
    <div class="col-xs-12">
      <!-- Horizontal Form -->
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title"><%= t('actions.edit') %> Hook</h3>
        </div>

        <%= render 'form', url: hook_path(id: @hook.id) %>
      </div>
    </div>
  </div>
</section>

app/views/hooks/index.html.erb
<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <%= link_to new_hook_path, class: "btn btn-primary" do %><i class="fa fa-plus"></i> <%= t('actions.new') %><strong> Hook</strong><% end %>

      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">Hooks</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <table id="example1" class="table table-bordered table-striped">
            <thead>
              <tr>
                <th><%= t('activerecord.attributes.hook.id') %></th>
                <th><%= t('activerecord.attributes.hook.url') %></th>
              </tr>
            </thead>

            <tbody>
              <% @hooks.each do |hook| %>
                <tr>
                  <td><%= link_to(hook.id, hook_path(hook)) %></td>
                  <td><%= link_to(hook.url, hook_path(hook)) %></td>

                  <td><%= link_to edit_hook_path(hook), class: "btn btn-warning" do %><i class="fa fa-pencil"></i> <%= t('actions.edit') %><% end %></td>

                  <td><%= link_to hook_path(hook), method: 'delete', data: {confirm: "Are you sure?"}, class: "btn btn-danger" do %><i class="fa fa-ban"></i> <%= t('actions.remove') %><% end %></td>
                </tr>
              <% end %>
            </tbody>

            <tfoot>
              <tr>
                <th><%= t('activerecord.attributes.hook.id') %></th>
                <th><%= t('activerecord.attributes.hook.url') %></th>
              </tr>
            </tfoot>
          </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</section>
<!-- /.content -->

app/views/hooks/new.html.erb
<section class="content">  
  <div class="row">
    <div class="col-xs-12">
      <!-- Horizontal Form -->
      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title"><%= t('actions.new') %> Hook</h3>
        </div>

        <%= render 'form', url: hooks_path %>
      </div>
    </div>
  </div>
</section>

app/views/hooks/show.html.erb
<!-- Main content -->
<section class="content">
  <!-- Default box -->
  <div class="box box-info">
    <div class="box-header with-border">
      <h3 class="box-title">Hook</h3>
    </div>

    <div class="box-body">
      <p>
        <strong><%= t('activerecord.attributes.hook.id') %>: </strong>
        <%= @hook.id %>
      </p>

      <p>
        <strong><%= t('activerecord.attributes.hook.url') %>: </strong>
        <%= @hook.url %>
      </p>

      <p>
        <%= link_to edit_hook_path(@hook), class: "btn btn-warning" do %>
          <i class="fa fa-pencil"></i><%= t('actions.edit') %>
        <% end %>

        <%= link_to hooks_path, class: "btn btn-default" do %>
          <i class="fa fa-undo"></i><%= t('actions.back') %>
        <% end %>

        <%= link_to posts_path(hook_id: @hook.id), class: "btn btn-success" do %>
          <i class="fa fa-envelope"></i>Posts
        <% end %>
      </p>
    </div>
  </div>
  <!-- /.box -->

  <div class="box">
    <div class="box-header">
      <h3 class="box-title">POST
        <small>message</small>
      </h3>

      <!-- tools box -->
      <div class="pull-right box-tools">
        <button type="button" class="btn btn-default btn-sm" data-widget="collapse" data-toggle="tooltip" title="Collapse">
          <i class="fa fa-minus"></i>
        </button>

        <!--
        <button type="button" class="btn btn-default btn-sm" data-widget="remove" data-toggle="tooltip" title="Remove">
          <i class="fa fa-times"></i>
        </button>
        -->
      </div>
      <!-- /. tools -->
    </div>

    <!-- /.box-header -->
    <%= form_for(@post, class: "form-horizontal") do |f| %>
      <%= f.hidden_field :hook_id, value: @hook.id %>

      <div class="box-body">
        <div class="form-group">
          <%= f.text_area :message, class: "form-control", size: "30x6" %>
        </div>
      </div>

      <div class="box-footer">
        <%= f.submit class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>
</section>
<!-- /.content -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>CD² | WebHook | Server</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= csrf_meta_tags %>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

  <header class="main-header">

    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>CD²</b></span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b> Service CD²</b></span>
    </a>

    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
        	<%#= render 'shared/header_notifications' %>

          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!--<img src="dist/img/user2-160x160.jpg" class="user-image" alt="User Image">-->
              <span class="hidden-xs">Administrator</span>
            </a>

            <%#= render 'shared/dropdown_user_data' %>
          </li>
          <!-- Control Sidebar Toggle Button -->
          <li>
            <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
          </li>
        </ul>
      </div>

    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>Administrator</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>

      <%#= render 'shared/search_form' %>

      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <!--<li class="header">MAIN NAVIGATION</li>-->

        <li class="treeview">
          <%= link_to hooks_path do %>
            <i class="fa fa-list-alt"></i> <span>Hooks</span>
          <% end %>
        </li>

        <!--
        <li class="treeview">
          <a href="#">
            <i class="fa fa-files-o"></i>
            <span>Layout Options</span>
            <span class="pull-right-container">
              <span class="label label-primary pull-right">4</span>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/layout/top-nav.html"><i class="fa fa-circle-o"></i> Top Navigation</a></li>
            <li><a href="pages/layout/boxed.html"><i class="fa fa-circle-o"></i> Boxed</a></li>
            <li><a href="pages/layout/fixed.html"><i class="fa fa-circle-o"></i> Fixed</a></li>
            <li><a href="pages/layout/collapsed-sidebar.html"><i class="fa fa-circle-o"></i> Collapsed Sidebar</a></li>
          </ul>
        </li>

        <li>
          <a href="pages/widgets.html">
            <i class="fa fa-th"></i> <span>Widgets</span>
            <span class="pull-right-container">
              <small class="label pull-right bg-green">new</small>
            </span>
          </a>
        </li>

        <li class="treeview">
          <a href="#">
            <i class="fa fa-pie-chart"></i>
            <span>Charts</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/charts/chartjs.html"><i class="fa fa-circle-o"></i> ChartJS</a></li>
            <li><a href="pages/charts/morris.html"><i class="fa fa-circle-o"></i> Morris</a></li>
            <li><a href="pages/charts/flot.html"><i class="fa fa-circle-o"></i> Flot</a></li>
            <li><a href="pages/charts/inline.html"><i class="fa fa-circle-o"></i> Inline charts</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-laptop"></i>
            <span>UI Elements</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/UI/general.html"><i class="fa fa-circle-o"></i> General</a></li>
            <li><a href="pages/UI/icons.html"><i class="fa fa-circle-o"></i> Icons</a></li>
            <li><a href="pages/UI/buttons.html"><i class="fa fa-circle-o"></i> Buttons</a></li>
            <li><a href="pages/UI/sliders.html"><i class="fa fa-circle-o"></i> Sliders</a></li>
            <li><a href="pages/UI/timeline.html"><i class="fa fa-circle-o"></i> Timeline</a></li>
            <li><a href="pages/UI/modals.html"><i class="fa fa-circle-o"></i> Modals</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-edit"></i> <span>Forms</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/forms/general.html"><i class="fa fa-circle-o"></i> General Elements</a></li>
            <li><a href="pages/forms/advanced.html"><i class="fa fa-circle-o"></i> Advanced Elements</a></li>
            <li><a href="pages/forms/editors.html"><i class="fa fa-circle-o"></i> Editors</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-table"></i> <span>Tables</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/tables/simple.html"><i class="fa fa-circle-o"></i> Simple tables</a></li>
            <li><a href="pages/tables/data.html"><i class="fa fa-circle-o"></i> Data tables</a></li>
          </ul>
        </li>
        <li>
          <a href="pages/calendar.html">
            <i class="fa fa-calendar"></i> <span>Calendar</span>
            <span class="pull-right-container">
              <small class="label pull-right bg-red">3</small>
              <small class="label pull-right bg-blue">17</small>
            </span>
          </a>
        </li>
        <li>
          <a href="pages/mailbox/mailbox.html">
            <i class="fa fa-envelope"></i> <span>Mailbox</span>
            <span class="pull-right-container">
              <small class="label pull-right bg-yellow">12</small>
              <small class="label pull-right bg-green">16</small>
              <small class="label pull-right bg-red">5</small>
            </span>
          </a>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-folder"></i> <span>Examples</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="pages/examples/invoice.html"><i class="fa fa-circle-o"></i> Invoice</a></li>
            <li><a href="pages/examples/profile.html"><i class="fa fa-circle-o"></i> Profile</a></li>
            <li><a href="pages/examples/login.html"><i class="fa fa-circle-o"></i> Login</a></li>
            <li><a href="pages/examples/register.html"><i class="fa fa-circle-o"></i> Register</a></li>
            <li><a href="pages/examples/lockscreen.html"><i class="fa fa-circle-o"></i> Lockscreen</a></li>
            <li><a href="pages/examples/404.html"><i class="fa fa-circle-o"></i> 404 Error</a></li>
            <li><a href="pages/examples/500.html"><i class="fa fa-circle-o"></i> 500 Error</a></li>
            <li><a href="pages/examples/blank.html"><i class="fa fa-circle-o"></i> Blank Page</a></li>
            <li><a href="pages/examples/pace.html"><i class="fa fa-circle-o"></i> Pace Page</a></li>
          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-share"></i> <span>Multilevel</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
            <li>
              <a href="#"><i class="fa fa-circle-o"></i> Level One
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a href="#"><i class="fa fa-circle-o"></i> Level Two</a></li>
                <li>
                  <a href="#"><i class="fa fa-circle-o"></i> Level Two
                    <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                  </a>
                  <ul class="treeview-menu">
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                    <li><a href="#"><i class="fa fa-circle-o"></i> Level Three</a></li>
                  </ul>
                </li>
              </ul>
            </li>
            <li><a href="#"><i class="fa fa-circle-o"></i> Level One</a></li>
          </ul>
        </li>
        <li><a href="documentation/index.html"><i class="fa fa-book"></i> <span>Documentation</span></a></li>
        <li class="header">LABELS</li>
        <li><a href="#"><i class="fa fa-circle-o text-red"></i> <span>Important</span></a></li>
        <li><a href="#"><i class="fa fa-circle-o text-yellow"></i> <span>Warning</span></a></li>
        <li><a href="#"><i class="fa fa-circle-o text-aqua"></i> <span>Information</span></a></li>
        -->
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
  	<%= yield %>
  	<%#= render 'shared/main_content' %>
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.3.7
    </div>
    <strong>Copyright &copy; 2016 </strong> All rights reserved.
  </footer>

  <%#= render "shared/right_menu" %>
  
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>

</div>

<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>
</html>

app/views/posts/index.html.erb
<!-- Main content -->
<section class="content">
  <div class="row">
    <div class="col-xs-12">
      <%= link_to hook_path(@hook), class: "btn btn-default" do %><i class="fa fa-undo"></i> <%= t('actions.back') %><strong> Hook</strong><% end %>

      <div class="box box-info">
        <div class="box-header with-border">
          <h3 class="box-title">Posts</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <table id="example1" class="table table-bordered table-striped">
            <thead>
              <tr>
                <th><%= t('activerecord.attributes.post.message') %></th>
                <th><%= t('activerecord.attributes.post.created_at') %></th>
              </tr>
            </thead>

            <tbody>
              <% @posts.each do |post| %>
                <tr>
                  <td><%= link_to("#{post.message[0, 30]}...", post_path(post)) %></td>
                  <td><%= DateTime.parse(post.created_at).strftime("%H:%M:%S - %m/%d/%Y") %></td>
                </tr>
              <% end %>
            </tbody>

            <tfoot>
              <tr>
                <th><%= t('activerecord.attributes.post.message') %></th>
                <th><%= t('activerecord.attributes.post.created_at') %></th>
              </tr>
            </tfoot>
          </table>
        </div>
        <!-- /.box-body -->
      </div>
      <!-- /.box -->
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->
</section>
<!-- /.content -->

app/views/posts/show.html.erb
<!-- Main content -->
<section class="content">
  <!-- Default box -->
  <div class="box box-info">
    <div class="box-header with-border">
      <h3 class="box-title">Post</h3>
    </div>

    <div class="box-body">
      <p>
        <strong><%= t('activerecord.attributes.post.hook') %>: </strong>
        <%= @post.hook.url %>
      </p>

      <p>
        <strong><%= t('activerecord.attributes.post.message') %>: </strong>
        <%= @post.message %>
      </p>

      <p>
        <strong><%= t('activerecord.attributes.post.created_at') %>: </strong>
        <%= DateTime.parse(@post.created_at).strftime("%T - %m/%d/%Y") %>
      </p>

      <p>
        <%= link_to posts_path(hook_id: @post.hook.id), class: "btn btn-default" do %>
          <i class="fa fa-undo"></i><%= t('actions.back') %>
        <% end %>
      </p>
    </div>
  </div>
  <!-- /.box -->
</section>
<!-- /.content -->

app/views/shared/_dropdown_user_data.html.erb
<ul class="dropdown-menu">
  <!-- User image -->
  <li class="user-header">
    <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">

    <p>
      Alexander Pierce - Web Developer
      <small>Member since Nov. 2012</small>
    </p>
  </li>
  <!-- Menu Body -->
  <li class="user-body">
    <div class="row">
      <div class="col-xs-4 text-center">
        <a href="#">Followers</a>
      </div>
      <div class="col-xs-4 text-center">
        <a href="#">Sales</a>
      </div>
      <div class="col-xs-4 text-center">
        <a href="#">Friends</a>
      </div>
    </div>
    <!-- /.row -->
  </li>
  <!-- Menu Footer-->
  <li class="user-footer">
    <div class="pull-left">
      <a href="#" class="btn btn-default btn-flat">Profile</a>
    </div>
    <div class="pull-right">
      <a href="#" class="btn btn-default btn-flat">Sign out</a>
    </div>
  </li>
</ul>

app/views/shared/_search_form.html.erb
<form action="#" method="get" class="sidebar-form">
  <div class="input-group">
    <input type="text" name="q" class="form-control" placeholder="Search...">
        <span class="input-group-btn">
          <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
          </button>
        </span>
  </div>
</form>